### ISSUE TITLE
Always showing Last provider state: preparing, iOS 16.1

### ISSUE THREAD

**Issue by defchen** [shamanec/GADS#109]
Hi, shamanec. I'm grateful for your wonderful job. 
I'm deploying and playing this project. My device is iPhone12 iOS16.1 (Dev mode on). WebDriverAgent app was installed into device and the sign was approved. But the web manager page is alway showing "Last provider state: preparing, t", and reinstalling the WebDriverAgent app automatically again and again. Could you help me? thx

**Comment by shamanec** [comment]
Hey @defchen have you checked the provider logs either in the UI or in the `provider.log` file in its folder? Make sure you run it with `--log-level=debug` flag and provide me with the errors that you find :)

**Comment by defchen** [comment]
yep, found error logs. 

{"event":"webdriveragent_xcodebuild","level":"debug","msg":"startWdaWithXcodebuild: Starting WebDriverAgent with command `[xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination platform=iOS,id=00008101-001C2150116A0022 -derivedDataPath ./build test-without-building]`","time":"2024-07-18T09:49:31+07:00"}
{"event":"ios_device_setup","level":"debug","msg":"goIOSForward: Forwarding port with command `[ios forward 60676 9500 --udid=00008101-001C2150116A0022]`","time":"2024-07-18T09:49:31+07:00"}
{"event":"ios_device_setup","level":"debug","msg":"goIOSForward: Forwarding port with command `[ios forward 60677 9100 --udid=00008101-001C2150116A0022]`","time":"2024-07-18T09:49:31+07:00"}
{"event":"ios_device_setup","level":"info","msg":"Successfully started WebDriverAgent for device `00008101-001C2150116A0022` forwarded on port 60675","time":"2024-07-18T09:49:36+07:00"}
{"event":"ios_device_setup","level":"debug","msg":"updateWebDriverAgent: Updating WebDriverAgent session and mjpeg stream settings for device `00008101-001C2150116A0022`","time":"2024-07-18T09:49:36+07:00"}
{"event":"device_setup","level":"debug","msg":"Starting Appium on device `00008101-001C2150116A0022` with command `[appium -p 60718 --log-timestamp --session-override --log-no-colors --default-capabilities {\"appium:udid\":\"00008101-001C2150116A0022\",\"appium:mjpegServerPort\":\"60677\",\"appium:clearSystemFiles\":\"false\",\"appium:webDriverAgentUrl\":\"http://localhost:60675\",\"appium:preventWDAAttachments\":\"true\",\"appium:simpleIsVisibleCheck\":\"false\",\"appium:wdaLocalPort\":\"60675\",\"appium:automationName\":\"XCUITest\",\"platformName\":\"iOS\",\"appium:deviceName\":\"iPhone\",\"appium:wdaLaunchTimeout\":\"120000\",\"appium:wdaConnectionTimeout\":\"240000\"}]`","time":"2024-07-18T09:49:36+07:00"}
{"event":"device_setup","level":"info","msg":"Starting Selenium grid node for device `00008101-001C2150116A0022` with command `[java -jar ./test/selenium.jar node --host 127.0.0.1 --config ./test/00008101-001C2150116A0022.toml --grid-url http://127.0.0.1:4444]`","time":"2024-07-18T09:49:41+07:00"}
{"event":"provider","level":"info","msg":"Resetting LocalDevice for device `00008101-001C2150116A0022` after error. Cancelling context, setting ProviderState to `init`, Healthy to `false` and updating the DB","time":"2024-07-18T10:52:42+07:00"}
{"event":"ios_device_setup","level":"error","msg":"goIOSForward: Error waiting `ios forward` to finish for device `00008101-001C2150116A0022` - signal: killed","time":"2024-07-18T10:52:42+07:00"}
{"event":"ios_device_setup","level":"error","msg":"goIOSForward: Error waiting `ios forward` to finish for device `00008101-001C2150116A0022` - signal: killed","time":"2024-07-18T10:52:42+07:00"}
{"event":"ios_device_setup","level":"error","msg":"goIOSForward: Error waiting `ios forward` to finish for device `00008101-001C2150116A0022` - signal: killed","time":"2024-07-18T10:52:42+07:00"}
{"event":"device_setup","level":"error","msg":"startAppium: Error waiting for `[appium -p 60718 --log-timestamp --session-override --log-no-colors --default-capabilities {\"appium:udid\":\"00008101-001C2150116A0022\",\"appium:mjpegServerPort\":\"60677\",\"appium:clearSystemFiles\":\"false\",\"appium:webDriverAgentUrl\":\"http://localhost:60675\",\"appium:preventWDAAttachments\":\"true\",\"appium:simpleIsVisibleCheck\":\"false\",\"appium:wdaLocalPort\":\"60675\",\"appium:automationName\":\"XCUITest\",\"platformName\":\"iOS\",\"appium:deviceName\":\"iPhone\",\"appium:wdaLaunchTimeout\":\"120000\",\"appium:wdaConnectionTimeout\":\"240000\"}]` command to finish, it errored out or device `00008101-001C2150116A0022` was disconnected - signal: killed","time":"2024-07-18T10:52:42+07:00"}
{"event":"device_setup","level":"error","msg":"Error waiting for Selenium Grid node command to finish, it errored out or device `00008101-001C2150116A0022` was disconnected - signal: killed","time":"2024-07-18T10:52:42+07:00"}

**Comment by shamanec** [comment]
WebDriverAgent seems to start successfully - it fails either with Appium or the Selenium Grid node commands. It's a bit hard to catch Appium errors because the command does not exit when a problem is found. I would suggest you first try to disable using Selenium Grid and try without it. If it still fails then you can find the respective device logs file and search through the Appium logs there - there might be an error displayed

**Comment by defchen** [comment]
I fixed errors above. I can connect devices. but new issue comes when I click any position on the screen mirror. It seems 
 it occurs on error positions.

 {"ts":1721310207935,"msg":"--\u003e POST /session/1e6415c3-0d8b-49b8-8506-a25c6caa937f/actions {\"actions\":[{\"type\":\"pointer\",\"id\":\"finger1\",\"parameters\":{\"pointerType\":\"touch\"},\"actions\":[{\"type\":\"pointerMove\",\"duration\":0,\"x\":66.0111706148408,\"y\":790.4407461155726,\"button\":0},{\"type\":\"pointerDown\",\"duration\":0,\"button\":0},{\"type\":\"pause\",\"duration\":10,\"button\":0},{\"type\":\"pointerUp\",\"duration\":0,\"button\":0}]}]}","appium_ts":"2024-07-18 13:43:27:935","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}
{"ts":1721310207938,"msg":"Calling AppiumDriver.performActions() with args: [[{\"type\":\"pointer\",\"id\":\"finger1\",\"parameters\":{\"pointerType\":\"touch\"},\"actions\":[{\"type\":\"pointerMove\",\"duration\":0,\"x\":66.0111706148408,\"y\":790.4407461155726,\"button\":0},{\"type\":\"pointerDown\",\"duration\":0,\"button\":0},{\"type\":\"pause\",\"duration\":10,\"button\":0},{\"type\":\"pointerUp\",\"duration\":0,\"button\":0}]}],\"1e6415c3-0d8b-49b8-8506-a25c6caa937f\"]","appium_ts":"2024-07-18 13:43:27:938","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}
{"ts":1721310207938,"msg":"Executing command 'performActions'","appium_ts":"2024-07-18 13:43:27:938","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}
{"ts":1721310207939,"msg":"Received the following W3C actions: [","appium_ts":"2024-07-18 13:43:27:938","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}
{"ts":1721310207939,"msg":"Preprocessed actions: [","appium_ts":"2024-07-18 13:43:27:938","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}
{"ts":1721310207949,"msg":"Matched '/actions' to command name 'performActions'","appium_ts":"2024-07-18 13:43:27:949","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}
{"ts":1721310207950,"msg":"Proxying [POST /actions","appium_ts":"2024-07-18 13:43:27:950","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}
{"ts":1721310208122,"msg":"Got response with status 500: {\"value\":{\"error\":\"unknown error\",\"message\":\"Invalid parameter not satisfying: point.x != INFINITY \u0026\u0026 point.y != INFINITY\",\"traceback\":\"(\\n\\t0   CoreFoundation                      0x00000001a7761e94 5CDC5D9A-E506-3740-B64E-BB30867B4F1B + 40596\\n\\t1   libobjc.A.dylib                     0x00000001a0a8b8d8 objc_exception_throw + 60\\n\\t2   Foundation                          0x00000001a2079b4c C431ACB6-FE04-3D28-B677-4DE6E1C7D81F + 5528396\\n\\t3   XCUIAutomation                      0x0000000102b8e494 -[XCPointerEventPath initForTouchAtPoint:offset:","appium_ts":"2024-07-18 13:43:28:122","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}
{"ts":1721310208123,"msg":"Matched W3C error code 'unknown error' to UnknownError","appium_ts":"2024-07-18 13:43:28:122","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}
{"ts":1721310208127,"msg":"Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Invalid parameter not satisfying: point.x != INFINITY \u0026\u0026 point.y != INFINITY","appium_ts":"2024-07-18 13:43:28:127","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}
{"ts":1721310208128,"msg":"\u003c-- POST /session/1e6415c3-0d8b-49b8-8506-a25c6caa937f/actions 500 193 ms - 1190 ","appium_ts":"2024-07-18 13:43:28:128","log_type":"1e6415c3","session_id":"1e6415c3-0d8b-49b8-8506-a25c6caa937f"}

**Comment by shamanec** [comment]
Please add a comment with the Appium problem you encountered and close the issue :)

**Comment by defchen** [comment]
It works by using custom WDA from your fork repo.

**Comment by Gnanaprakash22** [comment]
@defchen can you please let me know how have you fixed reinstalling the WebDriverAgent app automatically again and again
https://github.com/shamanec/GADS/issues/109#issue-2415072639
kindly let me know the steps as I'm also facing the same issue
