### ISSUE TITLE
There is no way to display and control iOS 17.4 Iphone 13 Xcode 15.3 Mac OS WebDriverAgent no custom

### ISSUE THREAD

**Issue by APOSHAml** [shamanec/GADS#111]
There is no way to display and control iOS, I attach screenshots and logs. Everything worked on another Mac Mini on iOS 16.6  In GADS version 1.40, Xcode 14.3.1

![Снимок экрана 2024-07-23 в 15 42 23](https://github.com/user-attachments/assets/9403112a-4ba0-4d64-887d-3240c7c23c37)

`{"event":"provider_setup","level":"info","msg":"Starting provider on port `10001`","time":"2024-07-23T15:41:47+03:00"}
{"event":"provider_setup","level":"info","msg":"Checking if Appium is installed and available on the host","time":"2024-07-23T15:41:47+03:00"}
{"event":"provider_setup","level":"info","msg":"Checking if Appium is set up and available on the host PATH","time":"2024-07-23T15:41:47+03:00"}
{"event":"provider_setup","level":"info","msg":"Provider runs on macOS and is set up to provide iOS devices","time":"2024-07-23T15:41:48+03:00"}
{"event":"provider_setup","level":"debug","msg":"Handling trailing slash of provided WebDriverAgent repo path if needed","time":"2024-07-23T15:41:48+03:00"}
{"event":"provider_setup","level":"debug","msg":"Provided WebDriverAgent repo path has no trailing slash, adding it","time":"2024-07-23T15:41:48+03:00"}
{"event":"provider_setup","level":"debug","msg":"Checking if provided WebDriverAgent repo path exists on the host","time":"2024-07-23T15:41:48+03:00"}
{"event":"provider_setup","level":"info","msg":"Checking if xcodebuild is set up and available on the host (Xcode is installed)","time":"2024-07-23T15:41:48+03:00"}
{"event":"provider_setup","level":"info","msg":"Building WebDriverAgent for testing using xcodebuild in path `/Users/Shared/appium-webdriveragent/` with command `/usr/bin/xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination generic/platform=iOS build-for-testing -derivedDataPath ./build` ","time":"2024-07-23T15:41:48+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"Command line invocation:","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination generic/platform=iOS build-for-testing -derivedDataPath ./build","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"User defaults from command line:","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"    IDEDerivedDataPathOverride = /Users/Shared/appium-webdriveragent/build","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"    IDEPackageSupportUseBuiltinSCM = YES","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"Prepare packages","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"ComputeTargetDependencyGraph","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"note: Building targets in dependency order","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"note: Target dependency graph (2 targets)","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"    Target 'WebDriverAgentRunner' in project 'WebDriverAgent'","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"        ➜ Explicit dependency on target 'WebDriverAgentLib' in project 'WebDriverAgent'","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"    Target 'WebDriverAgentLib' in project 'WebDriverAgent' (no dependencies)","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"GatherProvisioningInputs","time":"2024-07-23T15:41:49+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"","time":"2024-07-23T15:41:53+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"CreateBuildDescription","time":"2024-07-23T15:41:53+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"","time":"2024-07-23T15:41:53+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"ClangStatCache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-stat-cache /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk /Users/Shared/appium-webdriveragent/build/SDKStatCaches.noindex/iphoneos17.4-21E210-99a79c02cfa501706f5b564e46d84afe.sdkstatcache","time":"2024-07-23T15:41:53+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"    cd /Users/Shared/appium-webdriveragent/WebDriverAgent.xcodeproj","time":"2024-07-23T15:41:53+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-stat-cache /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk -o /Users/Shared/appium-webdriveragent/build/SDKStatCaches.noindex/iphoneos17.4-21E210-99a79c02cfa501706f5b564e46d84afe.sdkstatcache","time":"2024-07-23T15:41:53+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"","time":"2024-07-23T15:41:53+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"** TEST BUILD SUCCEEDED **","time":"2024-07-23T15:41:53+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"","time":"2024-07-23T15:41:53+03:00"}
{"event":"provider_setup","level":"info","msg":"Checking if go-ios binary is set up and available on the host PATH","time":"2024-07-23T15:41:53+03:00"}
{"event":"ios_device_setup","level":"info","msg":"Running setup for device `00008110-001230360E78401E`","time":"2024-07-23T15:41:58+03:00"}
{"event":"ios_device_setup","level":"info","msg":"Mounting DDI on device `00008110-001230360E78401E` with command `[ios image auto --basedir=./provider1/devimages]`, image will be stored/found in `./provider1/devimages`","time":"2024-07-23T15:41:58+03:00"}
{"event":"ios_device_setup","level":"debug","msg":"goIOSForward: Forwarding port with command `[ios forward 55675 9500 --udid=00008110-001230360E78401E]`","time":"2024-07-23T15:41:59+03:00"}
{"event":"ios_device_setup","level":"debug","msg":"goIOSForward: Forwarding port with command `[ios forward 55674 8100 --udid=00008110-001230360E78401E]`","time":"2024-07-23T15:41:59+03:00"}
{"event":"ios_device_setup","level":"debug","msg":"goIOSForward: Forwarding port with command `[ios forward 55676 9100 --udid=00008110-001230360E78401E]`","time":"2024-07-23T15:41:59+03:00"}
{"event":"webdriveragent_xcodebuild","level":"debug","msg":"startWdaWithXcodebuild: Starting WebDriverAgent with command `[xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination platform=iOS,id=00008110-001230360E78401E -derivedDataPath ./build test-without-building]`","time":"2024-07-23T15:41:59+03:00"}
{"event":"ios_device_setup","level":"info","msg":"Successfully started WebDriverAgent for device `00008110-001230360E78401E` forwarded on port 55674","time":"2024-07-23T15:42:03+03:00"}
{"event":"ios_device_setup","level":"debug","msg":"updateWebDriverAgent: Updating WebDriverAgent session and mjpeg stream settings for device `00008110-001230360E78401E`","time":"2024-07-23T15:42:03+03:00"}
{"event":"device_setup","level":"debug","msg":"Starting Appium on device `00008110-001230360E78401E` with command `[appium -p 55726 --log-timestamp --session-override --log-no-colors --default-capabilities {\"appium:udid\":\"00008110-001230360E78401E\",\"appium:mjpegServerPort\":\"55676\",\"appium:clearSystemFiles\":\"false\",\"appium:webDriverAgentUrl\":\"http://localhost:55674\",\"appium:preventWDAAttachments\":\"true\",\"appium:simpleIsVisibleCheck\":\"false\",\"appium:wdaLocalPort\":\"55674\",\"appium:automationName\":\"XCUITest\",\"platformName\":\"iOS\",\"appium:deviceName\":\"Iphone 13\",\"appium:wdaLaunchTimeout\":\"120000\",\"appium:wdaConnectionTimeout\":\"240000\"}]`","time":"2024-07-23T15:42:03+03:00"}
`

`{"ts":1721738524246,"msg":"Welcome to Appium v2.11.2 (REV c92adb3c479d70bb29f4399a808c972ef41510e7)","appium_ts":"2024-07-23 12:42:04:242","log_type":"Appium","session_id":""}
{"ts":1721738524248,"msg":"Non-default server args:","appium_ts":"2024-07-23 12:42:04:248","log_type":"Appium","session_id":""}
{"ts":1721738524250,"msg":"{ logNoColors: true, logTimestamp: true, port: 55726, sessionOverride: true }","appium_ts":"2024-07-23 12:42:04:250","log_type":"Appium","session_id":""}
{"ts":1721738524250,"msg":"Default capabilities, which will be added to each request unless overridden by desired capabilities:","appium_ts":"2024-07-23 12:42:04:250","log_type":"Appium","session_id":""}
{"ts":1721738524251,"msg":"{ 'appium:udid': '00008110-001230360E78401E',","appium_ts":"2024-07-23 12:42:04:251","log_type":"Appium","session_id":""}
{"ts":1721738524251,"msg":"The autodetected Appium home path: /Users/d_khlebest/.appium","appium_ts":"2024-07-23 12:42:04:251","log_type":"Appium","session_id":""}
{"ts":1721738524251,"msg":"Attempting to load driver xcuitest...","appium_ts":"2024-07-23 12:42:04:251","log_type":"Appium","session_id":""}
{"ts":1721738524252,"msg":"Attempting to load driver uiautomator2...","appium_ts":"2024-07-23 12:42:04:252","log_type":"Appium","session_id":""}
{"ts":1721738524255,"msg":"Requiring driver at /Users/d_khlebest/.appium/node_modules/appium-xcuitest-driver/build/index.js","appium_ts":"2024-07-23 12:42:04:255","log_type":"Appium","session_id":""}
{"ts":1721738524259,"msg":"Requiring driver at /Users/d_khlebest/.appium/node_modules/appium-uiautomator2-driver/build/index.js","appium_ts":"2024-07-23 12:42:04:259","log_type":"Appium","session_id":""}
{"ts":1721738525099,"msg":"XCUITestDriver has been successfully loaded in 0.847s","appium_ts":"2024-07-23 12:42:05:099","log_type":"Appium","session_id":""}
{"ts":1721738525101,"msg":"AndroidUiautomator2Driver has been successfully loaded in 0.847s","appium_ts":"2024-07-23 12:42:05:099","log_type":"Appium","session_id":""}
{"ts":1721738525112,"msg":"Appium REST http interface listener started on http://0.0.0.0:55726","appium_ts":"2024-07-23 12:42:05:112","log_type":"Appium","session_id":""}
{"ts":1721738525113,"msg":"You can provide the following URLs in your client code to connect to this server:","appium_ts":"2024-07-23 12:42:05:113","log_type":"Appium","session_id":""}
{"ts":1721738525114,"msg":"Available drivers:","appium_ts":"2024-07-23 12:42:05:113","log_type":"Appium","session_id":""}
{"ts":1721738525114,"msg":"  - xcuitest@7.24.1 (automationName 'XCUITest')","appium_ts":"2024-07-23 12:42:05:114","log_type":"Appium","session_id":""}
{"ts":1721738525115,"msg":"  - uiautomator2@3.7.4 (automationName 'UiAutomator2')","appium_ts":"2024-07-23 12:42:05:114","log_type":"Appium","session_id":""}
{"ts":1721738525115,"msg":"No plugins have been installed. Use the \"appium plugin\" command to install the one(s) you want to use.","appium_ts":"2024-07-23 12:42:05:114","log_type":"Appium","session_id":""}`

**Comment by shamanec** [comment]
I don't see any errors in the logs, but that 502 status code when checking the device health seems off. Are you using actual IP address for the provider or something like `localhost` or `127.0.0.1`? I don't believe I've seen this but I'll try to reproduce

**Comment by APOSHAml** [comment]
Thanks for the reply, I use localhost

**Comment by shamanec** [comment]
Okay, I'll test with `localhost`, I use actual local network IP address at all times and might have missed something. The custom WebDriverAgent should work the same way as mainstream WebDriverAgent as long as it's signed properly - what is the problem there, device not becoming available at all?

**Comment by khda** [comment]
It worked when I changed everything localhost to ip address! Thanks a lot

**Comment by APOSHAml** [comment]
It worked when I changed everything from localhost to an ip address! Thanks a lot

**Comment by shamanec** [comment]
Amazing, let me know if you encounter other issues so I can work on them :P
