### ISSUE TITLE
Appium-Python-Client cannot create new session on appium grid

### ISSUE THREAD

**Issue by ClasherGeek77** [shamanec/GADS#112]
Hi, shamanec.
I love your project so far but i find issues when running automation using appium grid with python client.
I tried other package from JS for debugging purpose which is working fine.

**JS Webdriverio** Working fine
POST http://10.21.80.5:8888/grid/session
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      'appium:automationName': 'UiAutomator2',
      'appium:ensureWebviewsHavePages': true,
      'appium:nativeWebScreenshot': true,
      'appium:newCommandTimeout': 3600,
      'appium:connectHardwareKeyboard': true
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:ensureWebviewsHavePages': true,
    'appium:nativeWebScreenshot': true,
    'appium:newCommandTimeout': 3600,
    'appium:connectHardwareKeyboard': true
  }
}

**Python Client**  No available device found
POST http://10.21.80.5:8888/grid/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'platformName': 'Android', 'appium:automationName': 'UiAutomator2'}}}

**error message**
Traceback (most recent call last):
  File "driver.py", line 17, in <module>
    driver = webdriver.Remote("http://10.21.80.5:8888/grid", desired_capabilities=caps, strict_ssl=False)
  File "/home/jtf01597/.pyenv/versions/3.8.16/lib/python3.8/site-packages/appium/webdriver/webdriver.py", line 257, in __init__
    super().__init__(
  File "/home/jtf01597/.pyenv/versions/3.8.16/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/jtf01597/.pyenv/versions/3.8.16/lib/python3.8/site-packages/appium/webdriver/webdriver.py", line 346, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
  File "/home/jtf01597/.pyenv/versions/3.8.16/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/jtf01597/.pyenv/versions/3.8.16/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: No available device found

 **python code**
```
# This sample code uses the Appium python client v2
# pip install Appium-Python-Client==2.11.0
# Then you can paste this into a file and simply run with : 'python filename.py'

from appium import webdriver

# For W3C actions
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.actions import interaction
from selenium.webdriver.common.actions.action_builder import ActionBuilder
from selenium.webdriver.common.actions.pointer_input import PointerInput

caps = {}
caps["platformName"] = "Android"
caps["appium:automationName"] = "UiAutomator2"

driver = webdriver.Remote("http://localhost:10000/grid", desired_capabilities=caps, strict_ssl=False)

import time
time.sleep(10)
driver.quit()

import logging

logger = logging.getLogger(__name__)
logger.error("done")
```

**Comment by ClasherGeek77** [comment]
=UPDATE=
I edit the appium python client source, changed the json req body to the same as the supposed to be working
POST http://10.21.80.5:8888/grid/session 
{"capabilities": {"alwaysMatch": {"platformName": "Android", "appium:automationName": "UiAutomator2", "appium:ensureWebviewsHavePages": true, "appium:nativeWebScreenshot": true, "appium:newCommandTimeout": 3600, "appium:connectHardwareKeyboard": true}, "firstMatch": [{}]}, "desiredCapabilities": {"platformName": "Android", "appium:automationName": "UiAutomator2", "appium:ensureWebviewsHavePages": true, "appium:nativeWebScreenshot": true, "appium:newCommandTimeout": 3600, "appium:connectHardwareKeyboard": true}}

it can create the new sessions

**Comment by shamanec** [comment]
Hey! Of course, I will check it out! As stated in the README I only tested with the latest Java client and I thought this is the usual payload 😅 I will create a new version, thanks for the report 🚀

**Comment by shamanec** [comment]
Done with #113 - v2.0.1

**Comment by ClasherGeek77** [comment]
yeah its all good. for this issue. thanks @shamanec
