### ISSUE TITLE
 Failed to get provider data from DB

### ISSUE THREAD

**Issue by Gnanaprakash22** [shamanec/GADS#119]
./GADS provider --nickname=iPhone Provider--mongo-db=192.168.113.95:27017 --log-level=debug --hub=http://192.168.113.95:10000
Preparing...
2024/08/26 00:24:13 Failed to get provider data from DB - mongo: no documents in result

I have started the hub and trying to start the provider to get the device online but i m getting error Failed to get provider data from DB

**Comment by Gnanaprakash22** [comment]
issue is resolved when changing the Provider name to Provider1

**Comment by shamanec** [comment]
Sorry about that, maybe I should mention in the README to avoid spaces in names 😅
