### ISSUE TITLE
Tap/Swipe actions are not working in application which operates in landscape mode as intended for iOS

### ISSUE THREAD

**Issue by Gnanaprakash22** [shamanec/GADS#121]
Click/Swipe actions are clicking at random places for application which operates in landscape mode.
In portrait application actions are smooth.

Also if possible please handle the screen resolution/viewport in landscape mode for better usability :)

To provide more context it is an unity application 

please let me know if you need further information

[Video [Link](https://drive.google.com/file/d/17idpAj127fRJAA_-A_DmvUFr30l1tfbG/view?usp=sharing)]

**Comment by shamanec** [comment]
Yeah, that is expected because landscape is not handled at all :D This will require some work because it will be hard to automatically find out the current mode when you switch it on the device - I will look into it though, the easiest solution will probably be to add a button with which you will manually tell the UI that you are currently on landscape/portrait

**Comment by Gnanaprakash22** [comment]
yes having a button for landscape/portrait works :)

**Comment by shamanec** [comment]
I'll create a release with this later today

**Comment by shamanec** [comment]
@Gnanaprakash22 v2.3.0. Let me know if something ain't right, also try to use your device landscape to your left(device right) :D

**Comment by Gnanaprakash22** [comment]
@shamanec awesome !!! thanks will test it out

**Comment by Gnanaprakash22** [comment]
@shamanec it is working fine but one lil problem the page is not responsive/scrollable to see Landscape/Portrait button

**Comment by shamanec** [comment]
I guess I have to reduce the responsive sizes even more, I am used to having a high resolution monitor and I forget about that 😅

**Comment by Gnanaprakash22** [comment]
speed is slow when accessing remotely through other system using the hub link

**Comment by shamanec** [comment]
I don't think there is anything I can do about that as stated in the FAQ - I use WebDriverAgent for both the interaction and streaming so it is as good as they provide it. I might add an option to reduce the FPS and quality even more but I can't guarantee this will help over remote access :(

**Comment by Gnanaprakash22** [comment]
@shamanec could you please implement long tap & drag and drop in landscape mode it is not working

**Comment by Gnanaprakash22** [comment]
> I'll check about the long tap but I can't make any promises on drag&drop - it doesn't exist right now, its not only on landscape

swipe is also not working for the app which i was checking

**Comment by shamanec** [comment]
Do you think you can create some sample Unity app I can use for testing the swipe? I see no reason why swipes would work in some apps and not in others, I am just using coordinates :|

**Comment by Gnanaprakash22** [comment]
please share me your gmail id

**Comment by shamanec** [comment]
tapanar6@gmail.com

**Comment by Gnanaprakash22** [comment]
shared please check

**Comment by shamanec** [comment]
The buttons are now moved to the right of the stream canvas so this should be fine - I will need more time to go over the tap/swipe actions because it seems its more complex than I anticipated :)

**Comment by shamanec** [comment]
@Gnanaprakash22 you can check out the latest 2.4.1 release - swipe and tap should work better, also touch&hold. You still can't drag n drop though, or maybe you can if the element accepts swiping action

**Comment by Gnanaprakash22** [comment]
sure thanks for the update @shamanec will check this

**Comment by Gnanaprakash22** [comment]
@shamanec swipe and tap works better in this build thanks
