### ISSUE TITLE
There should be a release/unblock device button from admin account to release the device , if the user has not released the devices.

### ISSUE THREAD

**Issue by Gnanaprakash22** [shamanec/GADS#128]
<img width="1438" alt="Screenshot 2024-11-08 at 12 54 55 PM" src="https://github.com/user-attachments/assets/f470e26c-d19e-4413-8f20-dd53e83d878f">

**Comment by shamanec** [comment]
I'll think about how to implement this, it will require a bit more changes to the current implementation but I guess it should be possible 👌

**Comment by shamanec** [comment]
@Gnanaprakash22 this is done on the latest release - if someone is controlling the device, then admin users will be able to force release the device from the device selection. The button is available only to admins and only for releasing devices that are manually controlled
![image](https://github.com/user-attachments/assets/231be911-219d-4d51-92a8-26a4247ba8de)

**Comment by Gnanaprakash22** [comment]
@shamanec thanks for the update very useful feature

**Comment by Gnanaprakash22** [comment]
@shamanec new version looks good but i found an issue , when user account is using the device and if release button is clicked from admin account ,  getting "Session terminated" popup but on refresh user account is still able to access the device.

**Comment by shamanec** [comment]
Yeah, that makes sense because the device is released and when you reload you are essentially occupying it from scratch - so this will remain as is. I will see if I can check if someone else occupied it after it was released so you don't somehow take control of it with reload
