### ISSUE TITLE
Question about auth

### ISSUE THREAD

**Issue by pbezpal** [shamanec/GADS#132]
Hello! In GADS, user credentials are stored in MongoDb and just checked against the user data from MongoDb?

**Comment by shamanec** [comment]
Yeah, pretty much! In general it is meant for individual and company usage where credentials security isn't much of an issue so I haven't really thought much about it 😅

**Comment by pbezpal** [comment]
Thank you

**Comment by pbezpal** [comment]
@shamanec I have another question, how long does the user's session last until he is thrown out on the authorization form?

**Comment by shamanec** [comment]
Hey, it lasts for 1 hour, but this is only if you don't do anything, I can't remember what I implemented but it should refresh on each request I believe 😅

**Comment by pbezpal** [comment]
Thank you very much
