### ISSUE TITLE
what's "device_providers"

### ISSUE THREAD

**Issue by zhangnan24** [shamanec/GADS#61]
as the title, I don't know what to write into this array。can you offer me some help? now I have several iPhone and data cables, and I am trying to do iOS remote control.

**Comment by shamanec** [comment]
Good point, I need to remove this array, initially it was used to poll the provided IP address for device provider instances, but after RethinkDB was introduced this is not actually used anymore. So this repo is just for the remote control UI. A provider is essentially a running instance of [GADS-devices-provider](https://github.com/shamanec/GADS-devices-provider) which is a server that sets up each device for remote control/Appium testing, then registers it in RethinkDB, then GADS picks up the device data from RethinkDB and shows the device as available. So to be able to remotely control devices you need:
1. RethinkDB set up and running.
2. GADS instance running.
3. One or more [provider](https://github.com/shamanec/GADS-devices-provider) instances running

RethinkDB, GADS and GADS-devices-provider can run on the same host or different hosts as long as they are on the same network.
So once you set up and run a `GADS-devices-provider` instance on the current host(or any other host), then the UI should be able to pick up the devices as long as everything is okay. Ignore the `device_providers` array :P

You can find my LinkedIn and Discord in my Github profile, do not hesitate to contact me on those channels for help or keep raising issues here or on the other repos and I'll do my best to help you! :)

**Comment by zhangnan24** [comment]
你好，你的邮件我已经收到，我将在阅读后尽快给你回复，谢谢来件∩_∩

**Comment by shamanec** [comment]
I removed the array from the `config.json` and updated the Readme to be more obvious that a provider instance should be available to provide devices. Imma keep this thread for potential questions or contact me on other channels as I've written in my first response :)

**Comment by zhangnan24** [comment]
你好，你的邮件我已经收到，我将在阅读后尽快给你回复，谢谢来件∩_∩
