### ISSUE TITLE
Android Device status keeps on changing

### ISSUE THREAD

**Issue by garjmegamind** [shamanec/GADS#89]
I have setup the things according to the readme. 

I got my android device connected but when I try to use the device from web, it shows "Device is unavailable".
I checked in provider administration and found the device status keeps changing from init -> preparing -> live and then again init.

Here is the screen recording.

https://github.com/shamanec/GADS/assets/107445528/1020d65e-b7a8-4a6d-88af-78ea08ca1b2b

What can be the possible issue?

**Comment by shamanec** [comment]
stale issue
