### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by Rugved1652** [shamanec/GADS#93]
Hey bro.. I know it's very silly question but I don't have any android experience,  I know go Lang and react can you make a video how to setup android stream.. please bro it will be much much useful for me

**Comment by shamanec** [comment]
Hey, I am not really sure what you want: a video on how to setup GADS in particular or just the Android video [stream](https://github.com/shamanec/GADS-Android-stream)? :)

**Comment by Rugved1652** [comment]
Yes.. exactly  that

**Comment by shamanec** [comment]
Exactly... which one of the two options? 😅

**Comment by Rugved1652** [comment]
Android part

**Comment by Rugved1652** [comment]
I already setup GO lang and React Part, but unable to connect APK

**Comment by shamanec** [comment]
You don't have to "connect" APK per se, everything should happen automatically. Also you need to set up a [provider](https://github.com/shamanec/GADS-devices-provider) if you still haven't done it - I am not really sure what the problem is.

**Comment by shamanec** [comment]
> hey, I messed up with provider setup, thanks for help, working fine now

nice!
